function [cost] = cost_u(y, z, k, p, agg)
% This is the cost function on the interior of the capital utilization
% domain, ie ktilde < k
cost = ( agg.w ^ (2 - 2 * p.alpha) * ...
        (y / z) ^ 2 * ...
        (p.chi / k) ^ p.alpha ) ^ (1 / (2 - p.alpha)) * ...
       ( ((2 - 2 * p.alpha) / p.alpha) ^ (p.alpha / (2 - p.alpha)) + ...
         (p.alpha / (2 - 2 * p.alpha)) ^ ( (2 - 2 * p.alpha) / (2 - p.alpha) ) );
end