%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Florian\Google
%    Drive\FlorianProject\FirstModelRoughTrends\Yuriy_data\FRED_manufacturing_data\Output_asymmetry.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2014/04/16 13:18:03

%% Initialize variables.
filename = 'Output_asymmetry.csv';
delimiter = ',';
startRow = 4;
endRow = 34;

%% Format string for each line of text:
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%*s%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', delimiter, 'HeaderLines', startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
workweekcapital = dataArray{:, 1};
capacityutil = dataArray{:, 2};
industrialprod = dataArray{:, 3};

%% Clear temporary variables
clearvars filename delimiter startRow endRow formatSpec fileID dataArray ans;